# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    
    config.vm.network :forwarded_port, guest: 3306, host: 3306
    config.vm.network "private_network", ip: "10.0.0.100", type: "dhcp", auto_config: true

    config.vm.provision :shell, :path => "install.sh"

    config.vm.synced_folder "./data", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
end
